services:
  osrm-russia-car:
    container_name: "osrm-russia-car"
    image: "ghcr.io/project-osrm/osrm-backend:latest"
    volumes:
      - "./osrm/russia-car:/data"
    command: "osrm-routed --algorithm mld /data/russia-latest.osrm"
    restart: unless-stopped

  osrm-russia-bicycle:
    container_name: "osrm-russia-bicycle"
    image: "ghcr.io/project-osrm/osrm-backend:latest"
    volumes:
      - "./osrm/russia-bicycle:/data"
    command: "osrm-routed --algorithm mld /data/russia-latest.osrm"
    restart: unless-stopped

  osrm-russia-foot:
    container_name: "osrm-russia-foot"
    image: "ghcr.io/project-osrm/osrm-backend:latest"
    volumes:
      - "./osrm/russia-foot:/data"
    command: "osrm-routed --algorithm mld /data/russia-latest.osrm"
    restart: unless-stopped

networks:
  default:
    external: true
    name: osm-network
