# upstream nominatim-cyprus {
#     server nominatim-cyprus:8080 max_fails=25 fail_timeout=10s;
# }

# upstream nominatim-russia {
#     server nominatim-russia:8080 max_fails=25 fail_timeout=10s;
# }

# upstream nominatim-russia-szfo {
#     server nominatim-russia-szfo:8080 max_fails=25 fail_timeout=10s;
# }

# upstream nominatim-planet {
#     server nominatim-planet:8080 max_fails=25 fail_timeout=10s;
# }

server {
    # location /nominatim-cyprus/ {
    #     rewrite /nominatim-cyprus(/.*) $1 break;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_connect_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_read_timeout 60s;
    #     send_timeout 60s;
    #     proxy_pass http://nominatim-cyprus/;
    # }

    # location /nominatim-russia/ {
    #     rewrite /nominatim-russia(/.*) $1 break;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_connect_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_read_timeout 60s;
    #     send_timeout 60s;
    #     proxy_pass http://nominatim-russia/;
    # }

    # location /nominatim-russia-szfo/ {
    #     rewrite /nominatim-russia-szfo(/.*) $1 break;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_connect_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_read_timeout 60s;
    #     send_timeout 60s;
    #     proxy_pass http://nominatim-russia-szfo/;
    # }

    # location /nominatim-planet/ {
    #     rewrite /nominatim-planet(/.*) $1 break;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_connect_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_read_timeout 60s;
    #     send_timeout 60s;
    #     proxy_pass http://nominatim-planet/;
    # }
}
